import type { Metadata } from 'next'
import { Inter, Quicksand } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })
const pops = Quicksand({ subsets: ['latin'], weight:['300', '500', '400'] })

export const metadata: Metadata = {
  title: 'Lotería Fortuna',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pops.className}>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  )
}
